name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    stage1:
      runs-on: ubuntu-latest
      steps:
        - run: echo "::notice file=test.sh,line=1,endLine=10,title=Heloo::Just Testing"
        #- run: echo "::debug::Missing semicolon"
        #- run: echo "::error file=app.js,line=1::Missing semicolon"

    stage2:
      needs: stage1
      runs-on: ubuntu-latest
      steps:
        - run: echo "stage2 step"

    stage3:
      needs: stage1
      runs-on: ubuntu-latest
      steps:
        - run: echo "stage3 step"

